tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e3e4",
        "outline-variant": "#c1c8c2",
        "on-secondary-fixed-variant": "#6c3a00",
        "on-primary-fixed-variant": "#274e3d",
        background: "#f8f9fa",
        "on-primary-container": "#86af99",
        "secondary-fixed": "#ffdcc1",
        "inverse-primary": "#a5d0b9",
        "surface-container-highest": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        error: "#ba1a1a",
        "surface-dim": "#d9dadb",
        "secondary-fixed-dim": "#ffb878",
        "on-tertiary-container": "#d89b00",
        primary: "#012d1d",
        tertiary: "#342300",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#002114",
        surface: "#f8f9fa",
        "on-surface-variant": "#414844",
        "tertiary-container": "#503700",
        "secondary-container": "#fdad62",
        "on-tertiary-fixed": "#271900",
        secondary: "#8c4f09",
        "on-tertiary-fixed-variant": "#5e4100",
        "surface-tint": "#3f6653",
        "surface-container-high": "#e7e8e9",
        "surface-bright": "#f8f9fa",
        "primary-fixed": "#c1ecd4",
        "on-secondary-fixed": "#2e1500",
        "on-secondary-container": "#754000",
        "surface-container": "#edeeef",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffba27",
        "on-surface": "#191c1d",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-background": "#191c1d",
        "on-error": "#ffffff",
        outline: "#717973",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdea9",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed-dim": "#a5d0b9",
        "primary-container": "#1b4332",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        md: "24px",
        "margin-mobile": "20px",
        sm: "12px",
        xs: "4px",
        xl: "80px",
        lg: "48px",
        "margin-desktop": "64px",
        gutter: "16px",
      },
      fontFamily: {
        "headline-md": ["Quicksand"],
        "headline-lg": ["Quicksand"],
        "headline-lg-mobile": ["Quicksand"],
        "label-md": ["Open Sans"],
        "label-sm": ["Open Sans"],
        "body-md": ["Open Sans"],
        "display-lg": ["Quicksand"],
        "body-lg": ["Open Sans"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
};
